title: Eccode Chamber

markdown: kramdown
highlight: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
author: 'Jason Schein'
social:
    email: 'jasonschein@gmail.com'
    github: 'echochamber'
disqus_shortname: eccodechamber
googleanalytics: UA-54352885-1
BASE_URL: 'http://echochamber.github.io'
gems:
    - jekyll-paginate